
name: Deploy to EC2

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-actions@v0.1.7
      with:
        host: 35.154.207.146
        username: ec2-user
        key: ${{ secrets.EC2_SSH-KEY }}
        scripts: |
          cd /usr/share/nginx/html
          git pull origin main
